"""V_02__add_column_user

Revision ID: 9f45f5efe241
Revises: 374337de37dd
Create Date: 2023-09-01 15:10:05.639520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f45f5efe241'
down_revision: Union[str, None] = '374337de37dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_varified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp')
    op.drop_column('users', 'is_varified')
    # ### end Alembic commands ###
